### ISSUE TITLE
Add salt-cloud support

### ISSUE THREAD

**Issue by stdevel** [latenighttales/alcali#207]
**Describe the feat you'd like**
First of all - thanks for your work! I really like the interface and functionality - it's a great alternative to the commerical SaltStack Enterprise for the most basic tasks.

It would be extremely handy to also have the possibility to control `salt-cloud` via the web interface - e.g. for deploying new machines on-premises or in the cloud.

Is such a functionality planned?

**Is your feature request related to a problem? Please describe.**
It's not a problem - I'm jussing missing the functionality to deploy new machines using the shiny web UI.

**Additional context**
-

**Comment by claudekenni** [comment]
A orchestrate state using client type runner with the cloud modules should help with this.
May not be as integrated as needed, but should provide basic functionality

something like this may help get you started:
This is an example for VMware.
```
create_instance:
  salt.runner:
    - name: cloud.create
    - provider: {{ provider}}
    - instances: 
      - {{ instances}}
    - datacenter: datacenter
    - clonefrom: template 
    - cluster: cluster
    - num_cpus: 2
    - memory: 4GB
    - datastore: datastore
```
