### ISSUE TITLE
Issues in manage.py and packages/clean.sls

### ISSUE THREAD

**Issue by batgranny** [latenighttales/alcali#421]
Hi, 

I'm running the saltstack formula and I'm getting the following error:

```
----------
          ID: alcali-config-migrate-db-provision-cmd-run
    Function: cmd.run
        Name: ./manage.py migrate
      Result: False
     Comment: Command "./manage.py migrate" run
     Started: 11:47:34.647293
    Duration: 104.964 ms
     Changes:
              ----------
              pid:
                  7518
              retcode:
                  1
              stderr:
                    File "./manage.py", line 16
                      ) from exc
                           ^
                  SyntaxError: invalid syntax

```
should from exc be from exec?

also I found another issue in clean.sls:

```
alcali-package-clean-git-latest-file-absent:
  file.absent:
    -name: {{ alcali.deploy.directory }}/code

alcali-package-clean-virtualenv-absent:
  file.absent:
    -name: {{ alcali.deploy.directory }}/.venv
```

The -name lines were causing an issue.  I think it should be: 

```
alcali-package-clean-git-latest-file-absent:
  file.absent:
    - name: {{ alcali.deploy.directory }}/code

alcali-package-clean-virtualenv-absent:
  file.absent:
    - name: {{ alcali.deploy.directory }}/.venv
```

Al leat it worked when I did it that way.
